# WF Name

name: WF Name

# Controls when the action will run. Triggers the workflow on push or pull request on ONLY master branch

on:
  push:
    branches: master
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs ( build and deploy )
  build:

    runs-on: ubuntu-latest

 


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        node-version: "14"

    - name: NPM Install
      run: npm install

    - name: GATSBY Build
      run: npm run build

    - name: zip build result
      run: tar -czvf build.tar.gz public 
    - name: archive zip
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build.tar.gz
        
  deploy:
    needs: 
      - build
        
    runs-on: ubuntu-latest

        
        
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: extract build
        run: tar -xzvf build.tar.gz
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: deploy to s3
        run: aws s3 sync ./public s3:/bucket name --acl public-read
        
